### PR TITLE
sdl: Use powershell script to make installing dependencies easier on Windows

### PR DESCRIPTION
**Pull request by Ekopalypse**
**UPDATED** to reflect the new way.
Once this gets merged the workflow for users would be
~~~
v install sdl
v run windows_install_dependencies.vsh
~~~
The installation script must be executed from the sdl module directory. 

To test provided examples or run own sdl applications users need to copy the needed
sdl dlls to the main application directory, like

~~~
D:\ProgramData\Compiler\v\modules\sdl>copy thirdparty\SDL2-2.0.8\lib\x64\SDL2.dll examples\basic_window
        1 file(s) copied.

D:\ProgramData\Compiler\v\modules\sdl>cd ..

D:\ProgramData\Compiler\v\modules>v -cc msvc run sdl\examples\basic_window\main.v

D:\ProgramData\Compiler\v\modules>v -cc gcc run sdl\examples\basic_window\main.v

D:\ProgramData\Compiler\v\modules>
~~~

Do you have any questions/suggestions? Let me know. If it doesn't make sense, feel free to close it.

tested on Windows7 x64 with Powershell 3 and Windows 10 x64 with Powershell 5.1

### CODE REVIEW

**Comment by Larpon** [comment]
Nice improvement!

I know we've discussed some things on Discord - but just to be clear:

Is there not any way this can be made version independant? Preferably the version info for SDL and the modules should be set in one place. And paths should be version free also. The reason for this is to ease maintenance and error factors because we have all the branches (master, 2.0.9, 2.0.10, 2.0.12, 2.0.14 - and soon also 2.0.16 and 2.0.18) that'll need to be adjusted accordingly. Having a more generic, V, way to install it would be better (maybe the version info could be read in from a file or sit on top of one file? And the paths be made version free?) So if you change SDL version mid-project you should be able to just run the commands again and the script(s) will make sure you're good to go. The version info was actually available in the module `v.mod` files which is now history... If all this could be done in V it would be much much easier to maintain and propagate to all branches. We have a zip decompressor available AFAIK - what else do we need to make a 100% V based install script/tool?

@spytheman any thoughts on this?

**Comment by Larpon** [comment]
... OpenSSL 🤦‍♂️ sorry

**Comment by Ekopalypse** [comment]
I assume that by version independence you are referring only to the paths used in a third party directory, correct, because at some point it is necessary to know the specific version number.

Let me try to explain how this can/should work according to my current understanding:

1. the user uses v install to install the sdl module.
With this option, only the current master branch is used and the user has no way to switch to other versions

2. the user uses git clone to install the sdl module.
Here the user can check out different versions

No other option is needed or expected.

From the script point of view, these are the steps and questions that need to be performed/answered.
E.g. for the main sdl package (other packages have the same requirements, as far as I know)
1. create a third-party directory
	What if a directory with this name already exists?
		Use it.
	What if a file with this name exists?
		Hmmm ... at the moment this case is not foreseen
	Should a random directory possibly be created?
2. download the zip file
	Where is the download?  
		OK, the information is included in the script
	Where to download? 
		Directory from step 1
	What if there is already a file or directory with the name to be saved? 
		Currently a file is being overwritten, the case of a directory with the same name is not foreseen.

3. unpacking the downloaded package
	Where to unpack? 
		To the same directory where the download is located.
	What if there is already a directory or FILE with that name?
		Delete it? Abort and tell the user that this is the case?

4. rename the newly created directory with a generic name.
	How would the script know which directory was created in step 2? This information is not known beforehand.
		Simple solution: keep track of what was in the download directory before extraction and compare it with what is in it after extraction.
			Prone to errors as there is no unique state for the script to rely on. What if a user abuses the third-party directory?
		More complex solution: don't extract the zip first, but check what the resulting directory name is and then act accordingly.
			This needs to be investigated.

In any case, the script needs to know the version numbers to expand the links to download the zip files.
It could be that it additionally needs to know the name of the directory that is created in step 2, since it was not possible to retrieve it automatically.
By this I don't mean that you can decide for yourself what the name is, but that the zip file specifies which directory is created.

That would be one way I can think of to make it more general. Each branch would then have a unique version of the powershell script, differing only in the version number (-> resulting link) and maybe in the extreme directory names.

By the way, what should be done if one of the steps fails? Currently the script aborts and the user has to remove the broken installation manually, in case of git clone, in case of v install v remove can be used, but the sdl directory is still there and has to be deleted by the user.

**Comment by spytheman** [comment]
> Is there not any way this can be made version independant?

Imho, it is better for the paths to be version dependent imho, because downloading/unpacking/overwriting existing files is not cheap, and is prone to errors, that can not be handled conveniently in powershell script, without complicating it unnecessarily.

Even if it was a v script instead, changing a few strings is easier than maintaining complicated logic and then testing all the ways it can break.

**Comment by spytheman** [comment]
I just thought of something - the problem that powershell solves, is having a working way to download and unzip files, without dependencies, but the logic can be independent from it.

We just need 2 powershell scripts:
a) one that can download any URL.
b) another that can unzip any zip file.

All the rest can be done through a V script indeed, that just calls the above with `os.execute()`

**Comment by Ekopalypse** [comment]
I have a day off on Tuesday and no commitments to date, so I think I can realize it by then, the easy part, and test on Windows 7 and Windows 10.
So something like `downloader(urls []string, destination string)`
and maybe unzip with the zip methods V, which I haven't tested yet, otherwise `unzipper(zips []strings, destination []strings) `?

**Comment by Larpon** [comment]
Awesome, I like the specialized script idea. 🙏

**Comment by Larpon** [comment]
@Ekopalypse sounds like a good idea, cool 😎 

I'm curious, is there a performance improvement over just singular versions of the calls and a loop?
I.e:
`download(url string, dest string)`
`unzip(zip string, dest string)`

**Review by Larpon — APPROVED** [review]
Great work!

**Comment by Larpon** [comment]
A great improvement for Windows users 🥳

**Comment by Larpon** [comment]
Can we test this is in CI somehow? 🤔

**Comment by Ekopalypse** [comment]
> Can we test this is in CI somehow? thinking

I have no experience with CI, but I would assume it should be possible.
I mean, in the end it's like any other V program, only with the precondition that it has to download something. Maybe creating a test that basically just includes all possible libraries and returns their version is enough, right?
Can I somehow try to simulate CI locally?

**Comment by Larpon** [comment]
Thanks! And sorry for the delay

**Comment by Larpon** [comment]
We'll look at the Windows CI in another PR

**Comment by Ekopalypse** [comment]
@Larpon - no problem, we each donate our spare time to this - it takes as long as it takes.
If there's anything I can do to get this or other V-related things tested/working on Windows, ping me. As long as I have time to do it, I will.

**Pull request merged**
